
name: 'Build DC' 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: yarn test
          env: |
            CI=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots/