name: Build

on: [push]

jobs:
  bulid:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Screenshot Tests
        run: |
          yarn install
          yarn test
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: screenshots/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: coverage/lcov.info
